[package]
name = "xmeans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
itertools = "0.13.0"
kmeans = { git="https://github.com/mfigurski80/kmean-rs" } 
statrs = "0.16.1"
